services:
  frontend:
 #   build:
     # context: ./frontend
    #  dockerfile: Dockerfile
    image: prasadnaik1310/lms-frontend:latest
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - pnpm_store:/pnpm
    environment:
      NODE_ENV: development
      PNPM_HOME: /pnpm
      TMPDIR: /tmp
      PATH: /pnpm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    security_opt:
      - no-new-privileges:true
    tty: true
    stdin_open: true
    entrypoint:
      - sh
      - -lc
      - |
        rm -rf /app/node_modules
        mkdir -p /app/node_modules
        cp -a /opt/frontend_node_modules/. /app/node_modules/
        mkdir -p /app/node_modules/.vite-temp
        chmod -R a+rwX /app/node_modules || true
        exec ./node_modules/.bin/vite --host 0.0.0.0 --port 5173
        services:
  backend:
  #  build:
   #   context: ./backend
    #  dockerfile: Dockerfile
    image: prasadnaik1310/lms-backend:latest
    ports:
      - "8080:8080"
    env_file:
      - ./backend/cmd/.env

  audit:
    #build:
    #  context: ./frontend
   #   dockerfile: Dockerfile
    image: prasadnaik1310/lms-frontend:latest
    profiles:
      - audit
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - pnpm_store:/pnpm
    environment:
      NODE_ENV: development
      PNPM_HOME: /pnpm
      TMPDIR: /tmp
      PATH: /pnpm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    security_opt:
      - no-new-privileges:true
    entrypoint:
      - sh
      - -lc
      - |
        rm -rf /app/node_modules
        mkdir -p /app/node_modules
        cp -a /opt/frontend_node_modules/. /app/node_modules/
        mkdir -p /app/node_modules/.vite-temp
        chmod -R a+rwX /app/node_modules || true
        exec pnpm audit

volumes:
  frontend_node_modules:
  pnpm_store:
  